Repository code-inflation/cfspeedtest, pull requests merged in 2023-09, with the labels that each got.

#8 Make project usable as a library by adding lib.rs
  .github/workflows/CI.yml
  Cargo.lock
  Cargo.toml
  examples/download_test.rs
  examples/latency_test.rs
  examples/simple_speedtest.rs
  src/lib.rs
  src/main.rs
  src/measurements.rs
  src/speedtest.rs
Labels: enhancement

#10 Expose run_tests & run_tests
  Cargo.lock
  Cargo.toml
  src/measurements.rs
  src/speedtest.rs
Labels: enhancement

#17 remove todo item - now tracked as github issue
  README.md
Labels: documentation

#18 upgrade deps
  Cargo.lock
Labels: dependencies

#19 bump to version 1.1.2
  Cargo.lock
  Cargo.toml
Labels: dependencies
